export const AppActionTypes = {
    START_REQUEST: 'START_REQUEST',
    START_NOTE_REQUEST: 'START_NOTE_REQUEST',

    FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
    FETCH_TAGS_FAILURE: 'FETCH_TAGS_FAILURE',
    ADD_TAG_SUCCESS: 'ADD_TAG_SUCCESS',
    ADD_TAG_FAILURE: 'ADD_TAG_FAILURE',
    DELETE_TAG_SUCCESS: 'DELETE_TAG_SUCCESS',
    DELETE_TAG_FAILURE: 'DELETE_TAG_FAILURE',
    UPDATE_TAG_SUCCESS: 'UPDATE_TAG_SUCCESS',
    UPDATE_TAG_FAILURE: 'UPDATE_TAG_FAILURE',

    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

    CREATE_NOTE_SUCCESS: 'CREATE_NOTE_SUCCESS',
    CREATE_NOTE_FAILURE: 'CREATE_NOTE_FAILURE',
    ERASE_NOTE: 'ERASE_NOTE',
    FETCH_NOTE_SUCCESS: 'FETCH_NOTE_SUCCESS',
    FETCH_NOTE_FAILURE: 'FETCH_NOTE_FAILURE',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    DELETE_NOTE_FAILURE: 'DELETE_NOTE_FAILURE',
    UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
    UPDATE_NOTE_FAILURE: 'UPDATE_NOTE_FAILURE',

    DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
    DELETE_FILE_FAILURE: 'DELETE_FILE_FAILURE',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',

    FETCH_NOTES_SUCCESS: 'FETCH_NOTES_SUCCESS',
    FETCH_NOTES_FAILURE: 'FETCH_NOTES_FAILURE',
    ERASE_NOTES: 'ERASE_NOTES',

    ERASE_ERROR: 'ERASE_ERROR',
};