export const AuthActionTypes = {
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    LOGOUT: 'LOGOUT',
    REFRESH_ACCESS_TOKEN_SUCCESS: 'REFRESH_ACCESS_TOKEN_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    ERASE_ERROR: 'ERASE_ERROR',
    ERASE_NO_REDIRECT: 'ERASE_NO_REDIRECT',
};